### ISSUE TITLE
References to  "Calendar"

### ISSUE THREAD

**Issue by allella** [agautsc/CfG-2#14]
I know a calendar is a more concrete idea, but the primary purpose of the API was not that CFG creates any particular thing, but rather that people could create things from the data.

I know getting people to trust and use the API is a ways off, so if you think calendar is the best way to sell the idea then that's fine. Though,  if there's a way to hit on the true purpose that's more exciting than saying "meetup api" then we could call it something else.

**Comment by agautsc** [comment]
References to calendar were changed when I understood that was the goal of the project. I've since changed the project name to Events PI, but I'm sure there are places where I left the calendar part in. Please point those places out and I'll make a change.

**Comment by allella** [comment]
Submitted a PR
